### ISSUE TITLE
The buttons are not available

### ISSUE THREAD

**Issue by Azuresword** [stephengold/jme-vehicles#5]
When I try to run the lattest program i used my own computer compiled the program **MavDemo1**  it pushed out some waring and errors when open the main menu the buttons are not gonnowork as the program“MavenDemo1.bat” which has already complied . its weird . I need to solve this program . please offer me any help

**Comment by Azuresword** [comment]
22:15:09: 正在执行 ':MavDemo1:MavDemo1.main()'…

> Task :MavLibrary:compileJava
> Task :MavCommon:compileJava
> Task :MavCommon:processResources
> Task :MavCommon:classes
> Task :MavCommon:jar
> Task :MavDemo1:compileJava
> Task :MavDemo1:processResources
> Task :MavDemo1:classes
> Task :MavLibrary:processResources
> Task :MavLibrary:classes
> Task :MavLibrary:jar

> Task :MavDemo1:MavDemo1.main()
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jme3.util.ReflectionAllocator (file:/C:/Users/dylan/.gradle/caches/modules-2/files-2.1/org.jmonkeyengine/jme3-core/3.5.0-beta4/f46d5e01ee0e7a4c19ddbc0a80967ad46553befd/jme3-core-3.5.0-beta4.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.jme3.util.ReflectionAllocator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
12�� 29, 2021 10:15:45 ���� com.jayfella.jme.vehicle.lemurdemo.MavDemo1 main
����: Assertions are enabled.
12�� 29, 2021 10:15:46 ���� com.jme3.renderer.opengl.GLRenderer setMainFrameBufferSrgb
����: Driver claims that default framebuffer is not sRGB capable. Enabling anyway.
12�� 29, 2021 10:15:47 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture Models/classic_motorcycle/textures/MTA_Metales_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:48 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture Models/classic_motorcycle/textures/MTA_Metales_2_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:48 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture Models/classic_motorcycle/textures/MTA_Luces_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:48 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture Models/classic_motorcycle/textures/MTA_Metales_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:48 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture Models/classic_motorcycle/textures/MTA_Metales_2_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:48 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture Models/classic_motorcycle/textures/MTA_Motor_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:48 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture Models/classic_motorcycle/textures/MTA_Pintura_Metalica_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:48 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture Models/classic_motorcycle/textures/MTA_Asiento_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:49 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture /Models/classic_motorcycle/textures/MTA_Metales_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:49 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture /Models/classic_motorcycle/textures/MTA_Metales_2_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:49 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture /Models/classic_motorcycle/textures/MTA_Metales_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
12�� 29, 2021 10:15:53 ���� com.jme3.material.Material checkTextureParamColorSpace
����: The texture Models/Tank/Tank_Occ_Rough_Metal.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 28s
9 actionable tasks: 9 executed
22:16:38: 执行完成 ':MavDemo1:MavDemo1.main()'。

**Comment by stephengold** [comment]
Thanks for letting me know.

I studied the warnings, and none of them are serious or unusual.

I'll attempt to reproduce this issue and reply here if I have questions.

**Comment by Azuresword** [comment]
Thanks a lot  I tried a night,i think The version befor 1.5.0 all have this problem, But The version 1.5.0 is working well, my team and me all think your work helped us a lot, on our JAVA lesson  we tried to use your program as a base , we made some Simulation of machine physics. Truly Excellent work.

**Comment by stephengold** [comment]
I'm glad to know you found it useful. I'd still like to understand what causes the failures you saw in older versions...
