### ISSUE TITLE
RAM Usage and Low FPS  after playing few minutes. At start 60 FPS but after few time 18 FPS. 

### ISSUE THREAD

**Issue by IndieDev99** [stephengold/jme-vehicles#8]

**Comment by stephengold** [comment]
How much RAM usage? And how measured?
Which JVM (i.e. OpenJDK 64-Bit Server VM build 11.0.17+8)?
Which platform (i.e. Windows or Linux)?
How built (per instructions in the README? downloaded v1.5.0 release? built from top-of-tree?)

**Comment by IndieDev99** [comment]
> How much RAM usage? And how measured?
> Which JVM (i.e. OpenJDK 64-Bit Server VM build 11.0.17+8)?
> Which platform (i.e. Windows or Linux)?
> How built (per instructions in the README? downloaded v1.5.0 release? built from top-of-tree?)

JRE 8
Windows 8.1 64 bit
Nvidia Quadro 2000 1gb ddr5 graphics 
OpenGL 4.3 
16GB RAM
4.2 GB Usage on start and 5 GB Usage with stuttering issues on 18 fps. 
I am running demo. "Maven demo".
 I am new to Java game development. Just wanted to test "how much optimized jmonkeyengine is ".

**Comment by stephengold** [comment]
Since you're evaluating JMonkeyEngine, I hope you tested other applications as well!

Thank you for the details provided. However, you didn't answer all my questions.

1. How was RAM usage measured?
2. Did you download the pre-built MavDemo1.zip? Or did you build the demo from the source code?

I have a couple ideas what might be causing the performance issue, but first I want to reproduce your test as closely as I can.

**Comment by IndieDev99** [comment]
> Since you're evaluating JMonkeyEngine, I hope you tested other applications as well!
> 
> Thank you for the details provided. However, you didn't answer all my questions.
> 
> 1. How was RAM usage measured?
> 2. Did you download the pre-built MavDemo1.zip? Or did you build the demo from the source code?
> 
> I have a couple ideas what might be causing the performance issue, but first I want to reproduce your test as closely as I can.

-) I didn't measured RAM by jme tools I measured it using windows 8.1 task manager.
-) No. I just downloaded old 2021 maven demo. Which is a .bat file in a sub directory of demo. I installed 64 bit JRE 1.8. 
-) Yes I tested other applications those were great like Post Water and Physics tests. 

....... I am Unity game engine user. I don't know much about java and jmonkeyengine but I want to learn. Jmonkeyengine is a great platform for 3D games.

**Comment by stephengold** [comment]
Thanks for working with me. I'll investigate and report back here.

At the very least, I should publish an updated release of this project!

**Comment by IndieDev99** [comment]
> Thanks for working with me. I'll investigate and report back here.
> 
> At the very least, I should publish an updated release of this project!

I will be waiting ! And will try when you upload demo again !

**Comment by stephengold** [comment]
I tried to reproduce this issue on my Windows 11 laptop. I downloaded the v1.5 release of MavDemo1.zip and ran MavDemo1.bat from Explorer. I played with it for 20 minutes and didn't observe any stutter or frame drops. At the end of 20 minutes, Task Manager showed the app ("OpenJDK platform binary") to be using 1876 MB of memory. I have several versions of Java installed; the one actually used was Temurin-17.0.3

There are many differences that might account for the negative result:
+ I used a different version of Windows (11 vs 8.1)
+ I used a different version of Java (Temurin-17.0.3 vs 1.8)  
+ Different hardware (32 GB vs 16 GB, GeForce RTX 2070 vs Quadro 2000)

I suspect that the Java version is the key difference here. I believe garbage collection in Java 17 is more efficient than in 1.8.

@IndieDev99 Is there any possibility of installing a later version of Java on your test machine? You can download recent Java from https://adoptium.net/temurin/releases/

**Comment by IndieDev99** [comment]
Thank You very much for everything ( for your time and kind reply). I will try it !!

**Comment by IndieDev99** [comment]
The problem was old dated graphics drivers and Windows 8.1 was not updated !

**Comment by stephengold** [comment]
Thank you for reporting the resolution of this issue. I'm glad it's solved.
